### ISSUE TITLE
A module cannot have multiple default exports

### ISSUE THREAD

**Issue by thednp** [thednp/svg-path-commander#12]
### Reported on
https://github.com/thednp/svg-path-commander/pull/11/files

### Possible fix

* open `svg-path-commander/types/svg-path-commander.d.ts`
* find 'declare module "svg-path-commander/src/parser/pathParser"'
* comment 'export default function PathParser(pathString: string): void;'

**Comment by thednp** [comment]
@ducminh53cth can you please test the latest master and report back any issue.

Thank you

**Comment by ducminh53cth** [comment]
oh I have test your latest master and it work well on my angular project.
Thanks so much

Vào 4:08, CN, 8 thg 5, 2022 thednp ***@***.***> đã viết:
