### ISSUE TITLE
Transforms on g elements

### ISSUE THREAD

**Issue by lordanubi** [thednp/svg-path-commander#16]
So I'm really really loving this plugin but it's kinda limited.
Sometimes when doing different transforms on the same path points, it's better to apply them to a group instead. This way in the final svg there will be more repeated d attributes (same path) and the overall file will be compressed better (gzip will benefit from repetitions).
Is there any way to take advantage of the module for this? 
In particular I love the fact that it's SSR and I can easily scale o flip paths around their own center without having to deal with transform-box and its compatibility issues. But still I need to apply the transforms in the group non in the path itself, do you think is possible to save some of the work done on the path transforming and bring it to the g element maybe using the matrix transform?
What's really annoying is in that case we can set the origin of the transform only for the rotate operation, but maybe with the Matrix transforms there's some difference? I'm not sure.

Any help is really appreaciated :)

**Comment by thednp** [comment]
What do you mean limited? Our script can do everything about **SVG Path** (2d/"3d" transforms, reverse, normalize, optimize, bbox, split, clockwise, lengths and points, etc); its only HTML "manipulation" is the conversion of other shapes to path.

Because I don't fully understand what you need, a codepen example would help better, but let me try and reply to your issue(s):
* **it's better to apply them to a group instead** in that case you might not need the script at all, a simple CSS transform to your `<g>` should work fine;
* **set the origin of the transform only for the rotate operation** all transform operations done via SVGPathCommander(pathString).transform() instance method uses the center point of that shape by **default** while the SVGPathCommander.transformPath(pathString) static method uses [0,0,0] point as transform origin, so you should know what works for you.

Other manipulation should be worked around its features, adding functionality from SVGO or other scripts would create additional redundant scripting for many more of us.

**Comment by lordanubi** [comment]
"What do you mean limited? Our script can do everything about SVG Path (2d/"3d" transforms, reverse, normalize, optimize, bbox, split, clockwise, lengths and points, etc); its only HTML "manipulation" is the conversion of other shapes to path."__
I know and that's perfect I just was wondering if there is any way to use this on a group of paths instead of each path individually without merging them. I was wondering if maybe the plugin can return a matrix transform value we can use on other elements as well.

_"it's better to apply them to a group instead in that case you might not need the script at all, a simple CSS transform to your <g> should work fine;"_
Yes that's what I'm talking about but the problem is about the trasnform-origin and the and the transform-box properties which are compatible only in modern browser and in the printing software or old image softwares.

"set the origin of the transform only for the rotate operation all transform operations done via SVGPathCommander(pathString).transform() instance method uses the center point of that shape by default while the SVGPathCommander.transformPath(pathString) static method uses [0,0,0] point as transform origin, so you should know what works for you."
Yes and that's really great I would like a matrix transform on a group with the center of the group picked as a transform origin instead of the default 0,0 of the svg viewBox.

If something is still not clear let me know.

**Comment by lordanubi** [comment]
I just noticed the "dommatrix" package you made is exaclty what I was looking for but seems like there is no way to also set trasnform-origin there, it would be really cool though

**Comment by thednp** [comment]
DOMMatrix is just that: a shim for the native [DOMMatrix](https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix) which will completely replace webkitCSSMatrix and SVGMatrix in the future versions.

You can use a custom origin for each path in the group, basically apply the same origin to all shapes as showcase [here](https://github.com/thednp/svg-path-commander#quick-guide).

A simple utility might work like this for you:

```js
// deconstruct your static methods
const { transformPath, pathToString } = SVGPathCommander;

function setGroupTransform(group, object) {
  [...group.getElementsByTagName('path')].forEach((path) => {
    const pathString = path.getAttribute('d');
    const transformation = transformPath(pathString, object);
    path.setAttribute('d', pathToString(transformation, 2)); // 2 decimals to use for value rounding
  });
}

// test
// given a <g viewBox="0 0 16 16">
// given a transformObject
const transformObject: { rotate: [15,0,0], origin: [8,8,8] };

setGroupTransform(yourGroup, transformObject);
```

Super easy.

**Comment by lordanubi** [comment]
Just to be more clear other than the compressing reasons I would like to point that applying the transform to each path individually is not the same as applying them on a group of paths or some merged paths. It might be the same for simple translate transforms but for scale rotation etc.. where the origin of the transform is important is different.
For example if you apply the flipX on each individual path you get a different result than applying the transform on the merged paths cause the origin will change accordingly

**Comment by thednp** [comment]
The DOMMatrix is accessible here: `SVGPathCommander.CSSMatrix`, so you can do:

```js
// this is how SVGMatrix origin looks like
const matrix = new SVGPathCommander.CSSMatrix().translate(x,y).scale(0.7).translate(-x,-y);

yourGroup.setAttribute('transform', matrix.toString())
```

**Comment by lordanubi** [comment]
This is great as well but as you can see from this example: https://codepen.io/andreafuturi/pen/eYVKeQJ
It still needs the transform-box property to work as expected, I guess applying the transforms on each path individually is for now still the best option we have (for compatibility reasons).
Unless you have some more thoughts on that you can close this.
Thank you so much for your contribution!

**Comment by thednp** [comment]
We have nothing for `transform-box`, that is something completely outside the scope of our script which was developed for [SVGMorph](https://thednp.github.io/kute.js/svgMorph.html), transforming font-icons to inline SVGs or other stuff.

**Comment by lordanubi** [comment]
Ok I managed to get to the solution, I'll put it here for anyone coming :) To make the groups transforms consistent to the path transforms these code should be used
`
const x = points.getBBox().width/2 + points.getBBox().x
const y = points.getBBox().height/2 + points.getBBox().y
const matrix = new SVGPathCommander.CSSMatrix().translate(x,y).scale(0.35).translate(-x,-y)`
or you can also directly apply the transforms on the group itself if you prefer
`
const x = points.getBBox().width/2 + points.getBBox().x
const y = points.getBBox().height/2 + points.getBBox().y
<g transform="translate(${x},${y}).scale(0.35).translate(${-x},${-y})"><path d="${points.toString()}" /> </g>`

Thanks again for all your kind help!
