### ISSUE TITLE
path2Curve produces wrong result when converting L command

### ISSUE THREAD

**Issue by xiaoiver** [thednp/svg-path-commander#17]
Path for testing:
```js
M57.063 -18.541L13.225 -18.203L0 -60L-13.225 -18.203L-57.063 -18.541L-21.399 6.953L-35.267 48.541L0 22.5L35.267 48.541L21.399 6.953Z
```

after `toCurve`, I changed some CSS style:

```css
fill: none;
stroke: red;
```

<img width="420" alt="截屏2022-06-21 下午3 04 24" src="https://user-images.githubusercontent.com/3608471/174737665-eb14f983-6420-47bf-b43a-a580184e99d8.png">

**Comment by thednp** [comment]
Thanks for the report, I believe this must be related to the latest optimizations, but will look into it asap.

**Comment by xiaoiver** [comment]
> Thanks for the report, I believe this must be related to the latest optimizations, but will look into it asap.

Thanks, I think the problem came from the following lines which calculate control points for cubic bezier:
https://github.com/thednp/svg-path-commander/blob/master/src/process/lineToCubic.js#L24-L29

**Comment by thednp** [comment]
Exactly.

**Comment by thednp** [comment]
@xiaoiver please test latest master, it's solved for me.

**Comment by thednp** [comment]
@xiaoiver can you please confirm the fix? We're ready to push the next v1.0.5 now.

**Comment by xiaoiver** [comment]
> @xiaoiver can you please confirm the fix? We're ready to push the next v1.0.5 now.

I found another bug about converting A command to C, this is my test path:
```
M7.34788079488412e-15,-120A120,120,0,0,1,95.46267154065043,-72.71092312934756L59.66416971290652,-45.44432695584223A75,75,0,0,0,4.592425496802574e-15,-75Z
```

It should look like this:

<img width="1000" alt="截屏2022-06-21 下午11 01 03" src="https://user-images.githubusercontent.com/3608471/174832415-1a74c40d-8e54-4fba-b9fb-580ad712ea52.png">

But after converting to curve, it became this:

<img width="1016" alt="截屏2022-06-21 下午11 01 53" src="https://user-images.githubusercontent.com/3608471/174832629-2b71dd44-decd-494d-a1b8-dbd3f6b5c8e5.png">

**Comment by thednp** [comment]
I found the problem, it's the `arcToCubic` that's messing things up, also an issue introduced with the ES5->ES6 changes.

Will come back with a fix asap. Stay tuned.

**Comment by thednp** [comment]
@xiaoiver please test. Now this works for me

![image](https://user-images.githubusercontent.com/6761246/174854120-04c069fb-3111-4b28-8941-711004d872fd.png)
