### ISSUE TITLE
Subdividing paths/curves?

### ISSUE THREAD

**Issue by dtgreene** [thednp/svg-path-commander#22]
Hi, I'm trying to use this package to convert an SVG into a series of line segments for plotting.  The only way I can think of is calling `getPointAtLength` at different intervals for each path.  Would this be a decent way of doing that?  I wasn't sure if it may be really inefficient or something.

I also thought about converting each path into a curve and then using something like [bezier.js](https://github.com/Pomax/bezierjs) package which has a way to subdivide Bezier curves _n_ times.

**Comment by thednp** [comment]
@dtgreene the `getPointAtLength` is the way to go, but [splitCubic](https://github.com/thednp/svg-path-commander/blob/master/src/process/splitCubic.ts) for cubic bezier segments has some different use cases.

**Comment by dtgreene** [comment]
Sweet! thanks
