### ISSUE TITLE
Scale transform doesn't take into consideration the origin property

### ISSUE THREAD

**Issue by lordanubi** [thednp/svg-path-commander#23]
Hi, I noticed these transformations take into consideration the origin:
```
if (flipY) pathCommander.transform({ rotate: [180, 0, 0], origin: groupCenter });
if (rotate) pathCommander.transform({ rotate, origin: groupCenter });
```
while this will still scale the path based on its own center instead of the given origin
`if (scale) pathCommander.transform({ scale, origin: groupCenter });`

Why is that?

**Comment by thednp** [comment]
What is  groupCenter?

**Comment by lordanubi** [comment]
It is obtained by merging the d attributes of all the paths we want to apply the transform, getting the viewbox of the unified path and than it is obtained with [bbox.cx,bbox.cy]

**Comment by thednp** [comment]
I want to see some code sample.

**Comment by lordanubi** [comment]
https://jsfiddle.net/Scanu/3fdLut4m/40/
Just made up a little fiddle to show the problem and i just realised that it is actually working  as expected. Will look further in my codebase to see what's going wrong. thank you very much for your help!

**Comment by lordanubi** [comment]
ok found the error in the rest of my code, will close the issue. thank you again for this wonderful tool! Have a nice day :)
