### ISSUE TITLE
About the lineToCubic algorithm.

### ISSUE THREAD

**Issue by entronad** [thednp/svg-path-commander#25]
In the current lineToCubic algorithm, the cp1 is at 1/2 between start and end points, and cp2 is at end point: https://github.com/thednp/svg-path-commander/blob/master/src/process/lineToCubic.ts
If please I would like to ask why not cp1 at 1/3 and cp2 at 2/3 between stat and end points?

Besides, Could you please tell me where is the old lineToCubic algorithm (https://github.com/thednp/svg-path-commander/blob/8bf14ca186cc87f8a687f9737421d3bcbad91388/src/process/lineToCubic.js) comes from, it seems rather complicated, why you pick it and why you replaced it finally.

Thanks!

**Comment by thednp** [comment]
The answer is simple: the previous formula wasn't correct, the [morph components](https://thednp.github.io/kute.js/svgCubicMorph.html) animation wasn't right. You can find previous versions on npm if you browse them.
