### ISSUE TITLE
Unable to import and use default export in vite/sveltekit

### ISSUE THREAD

**Issue by canadaduane** [thednp/svg-path-commander#26]
I'm trying to understand the cause of the following error when I `import SVGPathCommander from "svg-path-commander"` in a sveltekit project:

```
TypeError: __vite_ssr_import_1__.default is not a constructor
    at +page.svelte:4:8
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1973:22)
    at Object.default (root.svelte:42:40)
    at eval (/node_modules/@sveltejs/kit/src/runtime/components/layout.svelte:8:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1973:22)
    at root.svelte:41:39
    at $$render (/node_modules/svelte/internal/index.mjs:1973:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1981:26)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:180:29)
    at async Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:285:10)
```

I've created a test project / minimal replication here, which is simply a skeleton sveltekit project with the above import added:

https://github.com/canadaduane/test-not-a-constructor

It's almost like sveltekit can't see the esnext exported module. Is there additional configuration needed, or should it "just work"?

**Comment by canadaduane** [comment]
Update: Using a local branch of `svg-path-commander`, if I change the `package.json` to the following, it works in sveltekit:

```
...
  "source": "src/index.ts",
  "main": "dist/svg-path-commander.js",
  "module": "dist/svg-path-commander.mjs",
  "types": "dist/svg-path-commander.d.ts",
...
```
(Note that `"esnext": "dist/svg-path-commander.mjs"` has been removed, and `"module"` now points to the `.mjs`).

So it appears sveltekit does not use the `"esnext"` package.json config to find es module dependencies.

**Comment by canadaduane** [comment]
It looks like the `"esnext"` entrypoint is "opt-in" at this point, and can be added via vite config:

```
export default defineConfig({
  plugins: [sveltekit()],
  resolve: {
    mainFields: ["browser", "esnext", "module"],
  },
});
```

I'm not 100% confident of the above order of priority, but it works for me.

**Comment by canadaduane** [comment]
It appears the issue is that rollup expects "module" to be esm:

```json
{
  "name": "my-package",
  "version": "0.1.0",
  "main": "dist/my-package.umd.js",
  "module": "dist/my-package.esm.js"
}
```

https://github.com/rollup/rollup/wiki/pkg.module

Can `svg-path-commander` follow this convention?

**Comment by thednp** [comment]
Hey there!

I follow vite in this case (I also updated package.json from one of the vanilla boilerplates) and yes it seems that things have changed a little over the last year, since Node v16+ now support ESM imports, perhaps it will and discourage the usage of CommonJS format in the future.

Meanwhile this will probably be something to work, I will test with your repo.
```json
{
  "source": "./src/index.ts",
  "main": "./dist/svg-path-commander.js",
  "module": "./dist/svg-path-commander.mjs",
  "types": "./dist/svg-path-commander.d.ts",
  "exports": {
    ".": {
      "require": "./dist/svg-path-commander.cjs",
      "import": "./dist/svg-path-commander.mjs"
    }
  },
}
```
I tested this with your repo and seems to be ok:
![image](https://user-images.githubusercontent.com/6761246/226101790-d399c912-4088-4368-8990-911c57892d1a.png)

So will update the lib as soon as I can. Will tag you then so you can check it.

Later.

**Comment by thednp** [comment]
Update: @canadaduane I've pushed a new version on npm, check it out and let me know OK? Also feel free to close the issue if we're good.

Thanks

**Comment by canadaduane** [comment]
This change works perfectly, thank you!
