### ISSUE TITLE
shapeToPath can't infer RectAttr type as param

### ISSUE THREAD

**Issue by canadaduane** [thednp/svg-path-commander#27]
Using this example from the readme:

```ts
const myRectAttr = {
	type: 'rect',
	x: 25,
	y: 25,
	width: 50,
	height: 50,
	rx: 5
};

const myRectPath = SVGPathCommander.shapeToPath(myRectAttr);
```

Results in this type error:

```
Argument of type '{ type: string; x: number; y: number; width: number; height: number; rx: number; }' is not assignable to parameter of type 'ShapeTypes | ShapeOps'.
  Property 'd' is missing in type '{ type: string; x: number; y: number; width: number; height: number; rx: number; }' but required in type 'GlyphAttr'.ts(2345)
```

Annotating `myRectAttr` with `const myRectAttr: RectAttr` solves the issue, but it seems like an unfortunate requirement.

I tried adding `ry` to the keys of myRectAttr, but this resulted in the same type error.

```ts
const myRectAttr = {
	type: 'rect',
	x: 25,
	y: 25,
	width: 50,
	height: 50,
	rx: 5,
	ry: 5
};

const myRectPath = SVGPathCommander.shapeToPath(myRectAttr);
```

(same error)

Edit to add:
typescript: 4.9.5
svg-path-commander: 2.0.4

**Comment by thednp** [comment]
I'm thinking `shapeToPath` should be a generic type `shapeToPath<T>( element: T, ...args)` but I will check that later today. Thanks

**Comment by thednp** [comment]
Update, @canadaduane `rx` and `ry` should be both optional for `RectAttr` as well as `ry` for `EllipseAttr`, I'm working on it.

**Comment by thednp** [comment]
@canadaduane the `rx` and `ry` params are now optional for `RectAttr` as well as `ry` for `EllipseAttr` for both `shapeToPath` and the new `shapeToPathArray`. I've written more details on my last commit.

**Comment by canadaduane** [comment]
Thanks!
