### ISSUE TITLE
can shapeToPath return a PathArray or SVGPathCommander?

### ISSUE THREAD

**Issue by canadaduane** [thednp/svg-path-commander#28]
I'd like to be able to call `shapeToPath` and chain it with `transform`, like this:

```ts
SVGPathCommander.shapeToPath({
	type: 'rect',
	x: center[0],
	y: center[1],
	width,
	height,
	rx: radius,
	ry: radius
})
.transform({
	origin: [0, 0],
	translate: [x, y],
})
```

However, it appears `shapeToPath` returns a `<path ... >` element instead of a `PathArray` or `SVGPathCommander`, which means I cannot modify the result using all of the helpful transform functions, afaict.

**Comment by thednp** [comment]
Yea, we might need a `shapeToPathArray` utility.

**Comment by thednp** [comment]
@canadaduane please check the latest master. If all good we have 2.0.5 released later today.

**Comment by thednp** [comment]
So you have `shapeToPathArray` now, you can just do:


```js
import { shapeToPathArray, transformPath } from 'svg-path-commander';

const myAttr = {
	type: 'rect',
	x: center[0],
	y: center[1],
	width,
	height,
	rx: radius,
	ry: radius
};

const myPathArray = shapeToPathArray(myAttr);

const myTransformedPathArray = transformPath(myPathArray, { rotate: [15,0,0] });

// OR 

const myTransformedPathArray = transformPath(shapeToPathArray(myAttr), { rotate: [15,0,0] });
```

I think this would suffice, I hope.
