### ISSUE TITLE
getPointAtLength results are very different compared with native svg getPointAtLength

### ISSUE THREAD

**Issue by eltapir** [thednp/svg-path-commander#3]
I compared SVGPathCommander.getPointAtLength() with the native svg path getPointAtLength().
The results are very different. More so, the results for the points at 0 length, half the length and full length are the same.

here is a codepen showing the results:

[codepen](https://codepen.io/krisheyse/pen/VwmLyOQ?editors=1011)

**Comment by thednp** [comment]
The codepen in issue is throwing me an error and I can't examine/fix it right away.

Like how much different is the result? Because I know about an acceptable margin of error, not exactly a major crack in the sky.

**Comment by eltapir** [comment]
I fixed the codepen :)

**Comment by thednp** [comment]
Yea, that looks like an acceptable margin of error to me and I will explain why.

I developed this script from SVGPath, Raphael and other sources, modernized everything for best modular implementation and performance basically the best JavaScript I know. The main purpose of this library is to provide the tools I need for KUTE.js for morph SVG components.

Now these sources use utilities from other sources to provide the computation of mostly what is clearly a best guess approximation. My input in those is basically none. With other words, SVGPathCommander should basically output same `getPathLength` as Raphael, our advantage is that we have a modern code base that is actually usable in Node.js and anything that can run JavaScript. You get some actual numbers you can use without the native SVG API.

If I remember correctly, in my calculation our output might actually be more accurate than the native implementation which is basically as old as the SVG 1.1 draft. Some say the native `getTotalLength` sometimes is wrong when certain SVG attributes are used, perhaps [this](https://github.com/juliangarnier/anime/issues/155) can give you a hint. Basically non-Chrome browsers, as well as early Chrome, used to throw a wide range of values around.

So yea, take it from here.

**Comment by eltapir** [comment]
For completeness I made a new codepen and included Raphael, Snap.svg and also svg-path-properties. I think Raphael and Snap.svg use native functions so the results are the same as native svg. If the margin is acceptable for you, that's ok. That is not the problem though. The problem is that there is a wrong result if I try to find the point at 50% of the total length. It gives the same result as the point at length 0 (zero) or 1 (total length).
(in the codepen there is no red dot on the left side - at 'total length * .5)

[https://codepen.io/krisheyse/pen/dyOoKzj?editors=0111](url)

cheers :)

**Comment by eltapir** [comment]
the link does not seem to work. just put the url in the browser :)
[https://codepen.io/krisheyse/pen/dyOoKzj?editors=0111](url)

**Comment by thednp** [comment]
Alright, lemme throw this around:

* try changing the round option to something "more accurate", before the SVGPathCommander invokation, paste this code `SVGPathCommander.options.decimals = 9`
* lemme know how the numbers go

**Comment by thednp** [comment]
I think the numbers should be almost the same. 

However, I'm looking at the [original source](https://github.com/DmitryBaranovskiy/raphael/blob/b5fdbdc9850827eb49622cd0bc81b26025f8128a/raphael.js#L3960-L4000) from Raphael, which is a completely different implementation compared to [mine](https://github.com/thednp/svg-path-commander/blob/master/src/util/getPathLength.js).

My implementation is small and quick, but very close to the native calculation, better than svg properties :)

**Comment by thednp** [comment]
I will have a look, thanks for this awesome report.

**Comment by thednp** [comment]
So yea, Raphael = Snap.svg, they /both use native in the browser](https://github.com/DmitryBaranovskiy/raphael/blob/b5fdbdc9850827eb49622cd0bc81b26025f8128a/raphael.js#L4064-L4075), and the function I linked above in other environments or legacy browsers.

**Comment by thednp** [comment]
After I've set the rounding to 9 decimals in your example I can see the red dot :)

**Comment by eltapir** [comment]
Ok, I can see the red dot as well. Problem solved, thanks :)

**Comment by thednp** [comment]
It also works with 4 decimals :)

**Comment by thednp** [comment]
I think I will add 9 decimals to those methods by default.

**Comment by thednp** [comment]
@eltapir get ready to learn:

```js
const PCEllipseLength = SVGPathCommander.getPathLength(ELLIPSE_PATH_STRING); // 4 decimals
// Red: SVGPathCommander - length ellipse: 916.4210437745604

const snapEllipseLength = Snap.path.getTotalLength(ELLIPSE_PATH_STRING); // the real utility from SNAP, and not Element.getTotalLength()
// returns Green: Snap - length ellipse: 916.4210437748001

const rafEllipseLength = Raphael.getTotalLength(ELLIPSE_PATH_STRING); // the real Raphael utility
// returns Orange: Raphael - length ellipse: 916.4210437748001
```

I say that's incredibly "accurate", don't you think?

**Comment by eltapir** [comment]
Indeed, that's very very accurate.

**Comment by thednp** [comment]
OK now, you can check the latest version 0.1.2, you can now do 

```js
const pathLength = SVGPathCommander.getPathLength(pathString,decimals)
```

**Comment by thednp** [comment]
![image](https://user-images.githubusercontent.com/6761246/147422207-71ad11e8-e2f8-4af5-9d4e-d40933208a79.png)

Here's your test with the latest "master" version.

**Comment by thednp** [comment]
And now should be almost perfect:

![image](https://user-images.githubusercontent.com/6761246/147422464-5ad808a3-f159-4808-b192-582140f13ab1.png)
