### ISSUE TITLE
getSVGMatrix not exposed

### ISSUE THREAD

**Issue by justin-hackin** [thednp/svg-path-commander#34]
Previously you had stated this function could be imported as such 

```
import SVGPathCommander from 'svg-path-commander';
const { getSVGMatrix } = SVGPathCommander;
```

but that didn't work and, looking at the code, it appears as though you have not exported it in any way.

**Comment by thednp** [comment]
That is correct, I didn't think people would actually need that.

**Comment by thednp** [comment]
v 2.0.6 will have the method exported to public static.
