### ISSUE TITLE
create path from stroked shape/path

### ISSUE THREAD

**Issue by tsdexter** [thednp/svg-path-commander#39]
Is it possible to use this library (or any other that you know of) that can convert a shape like `rect`, `circle`, `path` with stroke properties to a new `path` that includes the stroke within the path without having stroke properties on the element? 

For example, if the original shape is a 2x2 square with a stroke width of 1 the new path would draw a 3x3 square.

**Comment by thednp** [comment]
I know [SVGO](https://github.com/svg/svgo) does many things, not sure if this is possible however.

**Comment by tsdexter** [comment]
Thanks for the response. I found [SVGFixer](https://docs.oslllo.com/svg-fixer/master/#/getting-started/basic-usage?id=svgfixer-constructor) which can do it with CLI/Node...looking at whether I can port it to the browser now.
