### ISSUE TITLE
pathToCurve 2 consecutive arcs produces different shape

### ISSUE THREAD

**Issue by neslho** [thednp/svg-path-commander#4]
Using the `pathToCurve` function to convert 2 consecutive arcs produces a different shape.

Here you can see the result of 2 arcs that form an ellipse converted to cubic beziers:
https://codepen.io/danohlsen/pen/GREgoMo
<img width="1041" alt="2arcs" src="https://user-images.githubusercontent.com/2502374/142669280-9db62f3f-bb98-4a79-8095-09d47d961474.png">

PS very useful lib BTW! 💙

**Comment by thednp** [comment]
Hello. Unfortunately I don't remember how to determine the arc flags right now, but I will have a look. Meanwhile, can you test if Raphael / similar library produce the same effect? At least I can know what/where to look for :)

**Comment by thednp** [comment]
Eh problem solved. A single character needed to be changed.

**Comment by thednp** [comment]
Proof everything is working:

![image](https://user-images.githubusercontent.com/6761246/142726144-96ab644e-61e9-4d14-b9b2-fe6150291637.png)

Paste computed value:

```
M20 50C20.000000000000004 57.69800358919501 45 62.509255832441895 65 58.66025403784439C74.2820323027551 56.87392608830357 80 53.57265589908164 80 50C80 42.30199641080499 55.00000000000001 37.490744167558105 35.00000000000001 41.33974596215561C25.717967697244916 43.12607391169643 20 46.42734410091836 20 50C20 50 20 50 20 50
```

**Comment by thednp** [comment]
Ok you can test the master for now, if anything, but if you confirm, we can push it to NPM asap.

Thanks

**Comment by neslho** [comment]
Looks good on my end.

![arc-test](https://user-images.githubusercontent.com/2502374/142743139-718290bd-dc82-4705-a301-e7f19e26bf16.png)

Thanks for the fast fix!
