### ISSUE TITLE
SVGPathCommander.transform() return the path that has 'NaN'

### ISSUE THREAD

**Issue by jglee96** [thednp/svg-path-commander#6]
Hello,
I try to transfrom SVG path. my code is like this,
```
const path = new SVGPathCommander(svgPath, {});
const pathMatrix: SVGPathCommander.transformObject = {
  translate: [x, y],
  rotate: angle,
  origin: [0, 0],
};
path.transform(pathMatrix);
```
The path has **NaN** position value.
I found that the function `projection2D(m, point2D, origin)` divide number by **0** when originZ is **0**. I think it cause **NaN** value.
When I use random number on z value of origin like this `origin: [0, 0, {random number}]`, it doesn't make **NaN**

**Comment by thednp** [comment]
Thanks for the report, I forgot to have it handle 2 values origin. Stay tuned.

**Comment by thednp** [comment]
@jglee96 please test latest master and let me know ;)

**Comment by jglee96** [comment]
It works! Thank you for fixing it quickly!
