### ISSUE TITLE
Feature Request clostestPoint & segmentOfPoint

### ISSUE THREAD

**Issue by Falke-Design** [thednp/svg-path-commander#7]
I searched through the internet but didn't found a library that supports `clostestPoint` and `segmentOfPoint`. I don't use your library (no need for this functions) but I saw that you are reagular committing and that you have already many nice features, so maybe you are interessed.

For `clostestPoint` I found [that code](https://bl.ocks.org/mbostock/8027637) (scroll down until `function clostestPoint`). It is working well.

I also would need the start and end point of the segment, so I would need `segmentOfPoint` but I haven't found solutions without the deprecated `pathSegList`.

**Comment by thednp** [comment]
I will have a look as soon as I get some time.

**Comment by thednp** [comment]
The `closestPoint` is easy to implement, already have it working somehow, I will need you to confirm how accurate it is.

However the `segmentOfPoint` is rather tricky, because the calculation is done to a `pathArray` converted to curve, a process in which the `curveArray` may not have the same amount of segments as the original path when that path has Arc segments. Nevertheless it's worth a try, will let you know when we're ready for some tests.

**Comment by Falke-Design** [comment]
Very nice, thanks for the quick response.

For `segmentOfPoint` I found this [polyfill](https://github.com/progers/pathseg) with `getPathSegAtLength`, another way would be maybe to parse the path into the segments and then check with the native SVG function [isPointInStroke](https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/isPointInStroke) which segment contains the point

**Comment by thednp** [comment]
@Falke-Design take a minute to check the latest master, let me know how it goes.

**Comment by Falke-Design** [comment]
Wow very nice! The calculation is so fast 😍

I have found a few things but none of them are important.
In the Wiki:
- `SVGPathCommander.parsePathString(string)` should be the first of the static functions, because it is needed for every other function
- Some of the static functions also support `string`, I suggest to remove it from the doku and in a later release remove it from the code. It makes it confusing if some function can be used with the path string and some not
- `SVGPathCommander.optimizePath(*pathArray*)` and `SVGPathCommander.reversePath(string | pathArray)` are not in the correct format
- Move `getPropertiesAtLength` and `getPropertiesAtPoint` to the bottom. First introduce each single function `getClosestPoint`, `getSegmentOfPoint` and then the function that return all values in one call `getPropertiesAtPoint`

Changes in functions:
- It would be nice if `SVGPathCommander.parsePathString(string)` would also accept an HTML-SVG-Element
- Return named properties instead of each value in `getPathBBox`: `bbox: [{x: x1, y: y1}, {x:x2, y:y2}], width, height, center: {x: cx, y: cy, z: cz}`
- Return in `getSegmentOfPoint` and `getPropertiesAtPoint().segment` the visible `end` and `start` point:
![grafik](https://user-images.githubusercontent.com/19800037/147664258-17c7bb06-53df-400f-820e-86539bd76f44.png)


New function:
- Sometimes it would be nice to take one or multiple segments and get one new path out of it
- I don't know if this is possible but cutting / splitting a path would be a nice thing. 
- `getVisibleBBox`: Get the bounds of the visible shape instead only of the points in the segments:
`getPathBBox`: ![grafik](https://user-images.githubusercontent.com/19800037/147663720-40ccfdb2-38bf-4ee2-baea-e5a1480510f4.png)
`getVisibleBBox`: ![grafik](https://user-images.githubusercontent.com/19800037/147663792-7488671b-816a-40c4-99be-ca9c7f4a06a9.png)
There is also an [alternative](https://github.com/elfalem/Leaflet.curve/blob/ace73f5bf264aefb2bbcdcf6f74955317459ed7c/src/leaflet.curve.js#L57) out there which uses the points of the curve but I don't like that one:
![grafik](https://user-images.githubusercontent.com/19800037/147664073-8ae839e0-7b70-4946-865a-2b9de6839800.png)


Thanks for your fantastic work!

**Comment by thednp** [comment]
I agree with some of the changes in regards to the wiki. Some parts of it need to be updated again, in fact I need to refactor it for better navigation and hierarchy.

> It would be nice if `SVGPathCommander.parsePathString(string)` would also accept an HTML-SVG-Element

This is something I might consider for the SVGPathCommander, the utility will stay as is, my KUTE.js needs it just like that.

More of my 2cents:
* I don't agree with changing the output structure of the `getPathBBox`; the native output is `{x, y, width, height}`, the original function author only added `{cx, cy, x2, y2}`, where I only added `cz` for 3D to 2D projections, which makes more sense, especially for those familiar with Raphael / SnapSVG;
* a feature for [splitting segments](https://github.com/thednp/svg-path-commander/blob/master/src/process/splitCubic.js) is implemented with my KUTE.js, I don't see other uses for splitting other types of segments, Line segments are easy, Arcs are impossible unless converted to Cubic-Bezier, but if need arises in the future, we might re-consider;

While I appreciate the time to write feedback and test, in short and for all other issues, unfortunately I don't afford the time to develop, test and document, I'm a super happy I've done something that is accurate, efficient and returns a good `getPointAtLength` as well as a `getTotalLength` in a single function `pathLengthFactory`. I'm also very happy with my own implementation of `normalizePath`, `reversePath` and `optimizePath`.

Besides that, feel free to research, write feedback and even contribute with your own work if you think it should benefit us all. I love that about open source.

**Comment by Falke-Design** [comment]
I found a bug in the segment calculation. When the point is on the path it always returns the first segment:
```
var point = {x: 650, y: 150};

// point is not on the path - it takes the closest point and then get the segment - correct
var props1 = SVGPathCommander.getPropertiesAtPoint(pathArray,point);

// point is on the path (closest) - always the first segment is returned - wrong
var closest = SVGPathCommander.getClosestPoint(pathArray, point)
var props2 = SVGPathCommander.getPropertiesAtPoint(path,closest);

console.log(props1,props2)
```
![grafik](https://user-images.githubusercontent.com/19800037/147696871-460c8073-df37-4a1f-a359-da113185af94.png)

https://jsfiddle.net/L9sy8xzt/

**Comment by thednp** [comment]
I already found the code line that's incorrect, but will have to have a look at it after some rest ;)

**Comment by thednp** [comment]
If you can test please edit `getPropertiesAtLength.js` line 73:

```js
  const segment = getPropertiesAtLength(path, bestDistance);
```
replace with

```js
  const segment = getPropertiesAtLength(path, bestLength);
```

or edit your built local file with the above change, let me know if that's the fix, I think I missed that due to lack of rest as usual.

**Comment by Falke-Design** [comment]
Yes this is it, is now perfectly working!

**Comment by thednp** [comment]
Alright, then I'm going to publish new version in a couple minutes. ;)

**Comment by thednp** [comment]
Sup @Falke-Design are you ready to test a new and improved build sometime early next week?

I've done some huge rework, thanks to testing with Cypress I found lots of ways to improve the code base, what do you say?

**Comment by Falke-Design** [comment]
@thednp Yes I can do some tests. Is it already in the current master branch?

**Comment by thednp** [comment]
Nop, not yet, I'm currently working hard on Cypress testing, will give you a buzz.

**Comment by thednp** [comment]
@Falke-Design ready to test. Have fun
