### ISSUE TITLE
Trim string before converting shape to path

### ISSUE THREAD

**Issue by Falke-Design** [thednp/svg-path-commander#8]
If there are two spaces at the end of the points-string, it convertes it to `0 0z` which results in a wrong path.

**Current**
```
<polygon id='poly' fill="#F7CD48" points="15,29.5 32,32 32,17 15,17  "/>
to:
<path id='polynew' fill="#F7CD48" d="M15 29.5L32 32L32 17L15 17L0 0z"/>
```

**Expected**
```
<polygon id='poly' fill="#F7CD48" points="15,29.5 32,32 32,17 15,17  "/>
to:
<path id='polynew' fill="#F7CD48" d="M15 29.5L32 32L32 17L15 17Lz"/>
```
If the spaces are removed it works: 
from `points="15,29.5 32,32 32,17 15,17  "` to `points="15,29.5 32,32 32,17 15,17"`

Demo: https://jsfiddle.net/8rfwm5yv/

**Comment by thednp** [comment]
Thanks for the find, will get to it asap.
