### ISSUE TITLE
flipX - origin is not iterable: Related to using in Vue 3 component?

### ISSUE THREAD

**Issue by brianakidd** [thednp/svg-path-commander#9]
I'm simply trying to execute the example code:

```
import SVGPathCommander from 'svg-path-commander';

const path = 'M0 0 L50 100';

const flippedPathString = new SVGPathCommander(path).flipX().toString();
```

but receive console error "origin is not iterable."  Is this related to executing inside a Vue component?  On the demo page (https://thednp.github.io/svg-path-commander/index.html), I can paste my data in, perform transformations, and receive expected output.

**Comment by thednp** [comment]
I'm not sure, but a test site would help.

I'm planning to add Cypress testing suite to SVGPathCommander and remove any remaining bugs.
Perhaps sooner than expected.

**Comment by tombigel** [comment]
@thednp I'm getting the same error, using the skypack version (https://www.skypack.dev/view/svg-path-commander)

The bug is in line 1807 in the unminified bundle:

If origin is not passed to any .transform() operation (also flipX/Y etc.) the transform function spreads to an object instead of an array - 
```
 } else {
      transform.origin = {...this.origin};
    }
```

should be :

```
 } else {
      transform.origin = [..this.origin];
    }
```

**Comment by tombigel** [comment]
I created a pr https://github.com/thednp/svg-path-commander/pull/10

**Comment by lordanubi** [comment]
Having the same problem in React but this doesn't fix it:
```
 } else {
      transform.origin = [...this.origin];
    } 
```

**Comment by thednp** [comment]
@lordanubi have a minute to produce a test repo.

**Comment by thednp** [comment]
@brianakidd I can confirm the fix is solid for me. I'm ready to push v0.1.26 to the cloud.

V0.2.0 will feature Cypress testing.

**Comment by brianakidd** [comment]
@thednp Sounds great.  Thanks

**Comment by thednp** [comment]
@lordanubi we're waiting for your confirmation.

**Comment by thednp** [comment]
@brianakidd @lordanubi @tombigel please test latest master and let me know how it goes, Cypress testing is added to the main class, later to add for all statics, have fun!

**Comment by lordanubi** [comment]
I'm not getting the error anymore with last version but I noticed that flipX() and flipY() do the same thing have you checked that?
Anyway thanks for your hard work! Keep it up :)

**Comment by thednp** [comment]
@lordanubi perhaps your shape is a square or a circle?

**Comment by lordanubi** [comment]
whooops sorry it was my setup buggin as fuck, it works like a charm! Thanks again you can definitely close this

**Comment by tombigel** [comment]
sorry, was on holiday.
